[project]
name = "ezsam-monorepo"
version = "0.0.0"
dependencies = []
requires-python = ">=3.9, <3.12"

[tool.pdm.dev-dependencies]
dev = [
    "-e app @ file:///${PROJECT_ROOT}/app",
    "-e docs @ file:///${PROJECT_ROOT}/docs",
]
