repos:
- repo: local
  hooks:
  - id: pdm-lock-check
    name: pdm-lock-check
    description: validate lock file when pyproject.toml changes
    entry: bash -c 'cd packages/cli && pdm lock --check'
    language: system
    pass_filenames: false
    files: ^packages/cli/pyproject.toml$
  - id: pdm-export-lock
    name: pdm-export-lock
    description: export locked packages to requirements.txt when pdm.lock changes
    entry: bash -c 'cd packages/cli && pdm export -o requirements.txt'
    language: system
    pass_filenames: false
    files: ^packages/cli/pdm.lock$
  - id: pdm-sync
    name: pdm-sync
    description: sync packages with lock file when switching branches
    entry: bash -c 'cd packages/cli && pdm sync'
    language: system
    pass_filenames: false
    stages:
      - post-checkout
      - post-merge
    always_run: true
