[project]
name = "ezsam"
version = "0.0.0"
description = "Extract foreground from images or video via text prompt" 
readme = "README.md"
requires-python = ">=3.9, <3.12"
license = {text = "AGPL-3.0-only"}
keywords = [
  "GroundingDINO",
  "Segment-Anything",
  "SAM",
  "SAM-HQ",
  "Grounded-Segment-Anything",
  "subject",
  "object",
  "foreground",
  "background",
  "filter",
  "extract",
  "select",
  "remove",
  "prompt",
  "subtract",
]
authors = [
  {name = "ae9is", email = "aegis.opensource@gmail.com"}
]
maintainers = [
  {name = "ae9is", email = "aegis.opensource@gmail.com"}
]
classifiers = [
  "License :: OSI Approved :: GNU Affero General Public License v3",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Scientific/Engineering :: Image Processing",
  "Topic :: Scientific/Engineering :: Image Recognition",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "opencv-python>=4.9.0.80",
    "numpy>=1.26.3",
    "supervision>=0.17.1",
    "filetype>=1.2.0",
    "segment-anything-hq>=0.3",
    "torch>=2.1.2",
    "torchvision>=0.16.2",
    "tqdm>=4.66.1",
    "rf-groundingdino>=0.1.2",
]

[project.urls]
"Homepage" = "https://github.com/ae9is/ezsam"
"Bug Reports" = "https://github.com/ae9is/ezsam/issues"
"Source" = "https://github.com/ae9is/ezsam/"

[project.scripts]
ezsam = "ezsam.app:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# ref: https://github.com/pdm-project/pdm/issues/2189
[tool.pdm.options]
lock = ["--no-cross-platform"]

[tool.pdm]
distribution = "true"

[tool.pdm.scripts]
lint = "ruff check src"
format = "ruff format ."
safety = { shell = "pdm export -o requirements.txt && safety check -r requirements.txt --bare" }
start = "python src/ezsam/app.py {args}"
clean = "rm -rf .venv .pdm-build .pdm-python .ruff_cache dist"

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.1.11",
    "pytest>=7.4.4",
    "safety>=2.3.5",
]

[tool.pdm.build]
excludes = ["./**/.git"]
package-dir = "src"
includes = ["src/ezsam"]
source-includes = ["tests", "../../LICENSE", "README.md"]

[tool.ruff]
exclude = [
  ".git",
  ".venv",
]
line-length = 120
indent-width = 2
target-version = "py311"

[tool.ruff.format]
quote-style = "single"
